project:
  type: website
  output-dir: docs
  resources:
    - blood_markers_plot.html
    - meds_plot.html
    - blood_markers_pivot.csv
    - reports.json
    - med_schedule.json

website:
  title: "Maladie - Health Tracking"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blood Markers"
        href: blood.qmd
      - text: "Medications"
        href: meds.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
